<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="weboniselab" failures="1" tests="6" name="org.webonise.gofaceoff.java.Login" time="92.016" errors="0" timestamp="11 Jan 2018 09:40:00 GMT" skipped="0">
  <testcase classname="org.webonise.gofaceoff.java.Login" name="loginThenClickBackLink" time="23.709"/>
  <testcase classname="org.webonise.gofaceoff.java.Login" name="validUsernameLogin" time="21.557"/>
  <testcase classname="org.webonise.gofaceoff.java.Login" name="validEmailLogin" time="24.219">
    <failure message="Error. Username does not appear first. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error. Username does not appear first. expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.webonise.gofaceoff.verificationPages.LoginVerification.verifyLoginAppearance(LoginVerification.java:15)at org.webonise.gofaceoff.java.Login.validEmailLogin(Login.java:22)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- validEmailLogin -->
  <testcase classname="org.webonise.gofaceoff.java.Login" name="isPasswordMasked" time="2.065"/>
  <testcase classname="org.webonise.gofaceoff.java.Login" name="invalidLogin" time="8.744"/>
  <testcase classname="org.webonise.gofaceoff.java.Login" name="blankLoginCredentials" time="11.722"/>
</testsuite> <!-- org.webonise.gofaceoff.java.Login -->
